### ISSUE TITLE
Country Code Validation Failure With Newer Versions of pycountry

### ISSUE THREAD

**Issue by vangesseld** [anexia-it/geofeed-validator#4]
Country code validation consistently fails when using pycountry 20.7.3. At some point it appears they changed the structure of their database, updating keys from 'alpha2' to 'alpha_2'

Calling `pycountry.countries.get(alpha2='US')` raises a KeyError on 'alpha2'

Calling `pycountry.countries.get(alpha_2='US')` produces the expected result. 

Updating lines [149](https://github.com/anexia-it/geofeed-validator/blob/fe0d40590518a89ee6f5f91e605d5b7a0e04533e/geofeed_validator/fields/base.py#L149) and [152](https://github.com/anexia-it/geofeed-validator/blob/fe0d40590518a89ee6f5f91e605d5b7a0e04533e/geofeed_validator/fields/base.py#L156) in fields/base.py seems to resolve the issue.

**Comment by vangesseld** [comment]
Opened #6

**Comment by vangesseld** [comment]
No problem, looking forward to the new release. Thanks for your work on this!

**Comment by rwielk** [comment]
Hi @vangesseld ,

looks all good, I built a 0.6.1 release which should solve yours issues thanks to your MR.
Thanks for your work, please reopen ticket if you still have any problems regarding this.

Thanks and BR
Raiko
